### ISSUE TITLE
Switching from 1.5.0 to 1.6.0 (or later) causes exception on app startup

### ISSUE THREAD

**Issue by zipgenius** [dotMorten/WinUIEx#80] opened 2022-09-12 16:50 UTC
I've just updated WinUIEx from 1.5.0 to 1.8.0 but my application crashes on startup and this is what I get. I tried to downgrade WinUIEx from 1.8.0 to 1.7.0 and 1.6.0 and it didn't change.
![image](https://user-images.githubusercontent.com/547604/189711142-e2ae71ef-321b-4624-b7f4-b60ae1c1a0e0.png)

**Comment by dotMorten** [comment] 2022-09-14 18:25
> I tried to downgrade WinUIEx from 1.5.0 to 1.7.0 and 1.6.0 and it didn't change.

Are you saying if you downgrade to 1.5.0 though, the problem goes away, indicating the issue started in 1.6.0?

**Comment by zipgenius** [comment] 2022-09-15 22:07
Yes. If I create a new project using 1.8.0 directly it works, but in my existing project I'm stuck to 1.5.0: updating WinUIEx to 1.6.0 or later, I get this result.

**Comment by dotMorten** [comment] 2022-11-14 20:03
Sorry for the slow response, but been pretty busy with life stuff. Any chance you could provide a simple sample that reproduces the problem? Sounds like a new project doesn't reproduce it. Otherwise I'd just be guessing what the problem is, and I'm terrible at guessing.

**Comment by dotMorten** [comment] 2023-04-13 04:46
Closing. If you have more info feel free to reopen

**Closed by dotMorten** 2023-04-13 04:46 UTC
Labels: More Info Needed
