### ISSUE TITLE
Window Width and White Border

### ISSUE THREAD

**Issue by tensei** [dotMorten/WinUIEx#203] opened 2024-12-18 13:16 UTC
Love your package! I have two problems, though:

1. After setting the width of the window, it still appears larger than expected.
2. I'm not sure if this is related to the package, but when I set presenter.SetBorderAndTitleBar(false, false);, I get a strange white border. Is there a way to hide it?

![image](https://github.com/user-attachments/assets/d0e21736-b158-47fb-b1a1-01ac46a8dc66)
![image](https://github.com/user-attachments/assets/9dc6acbc-0cac-4bd9-9682-93d0e929994a)

```xaml

<?xml version="1.0" encoding="utf-8" ?>

<winUiEx:WindowEx
    x:Class="MiddleClickScroll.Features.Overlay.CursorOverlayWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:winUiEx="using:WinUIEx"
    IsAlwaysOnTop="True"
    IsShownInSwitchers="False"
    PresenterKind="Overlapped"
    mc:Ignorable="d">

    <Window.SystemBackdrop>
        <winUiEx:TransparentTintBackdrop />
    </Window.SystemBackdrop>


    <Image
        Width="36"
        Height="36"
        Source="ms-appx:///Assets/scroll.png" />

</winUiEx:WindowEx>
```

**Comment by AkilanRagavaswamy** [comment] 2024-12-18 13:31
I dont think this is related to this package. What is the windows app SDK version which you use?

**Comment by tensei** [comment] 2024-12-18 13:35
@AkilanRagavaswamy  `1.7.241114004-experimantal1`

**Comment by AkilanRagavaswamy** [comment] 2024-12-18 13:36
Yeah I have updated my app to the latest stable SDK version `1.6.241114003`

I am also facing the same problem since today. Might be the cause for it.

**Comment by ghost1372** [comment] 2024-12-18 13:49
WinUI bug
https://github.com/microsoft/microsoft-ui-xaml/issues/9978

**Comment by dotMorten** [comment] 2024-12-18 17:42
Size: Duplicate of https://github.com/dotMorten/WinUIEx/issues/200 and
The border is WinUI bug as @ghost1372 linked to.

**Closed by dotMorten** 2024-12-18 17:42 UTC
